CREATE TABLE STUDENT(
StudentID INT IDENTITY(1,1) PRIMARY KEY,
L_Name VARCHAR(35),
F_Name VARCHAR(35),
Grade INT,
Gender BIT,
DOB DATE
);

CREATE TABLE ITEM(
ItemID INT IDENTITY(1,1) PRIMARY KEY,
Item_Name VARCHAR(35),
Item_QtyOnHand INT
);

CREATE TABLE MERIT(
MeritID INT IDENTITY(1,1) PRIMARY KEY,
Merit_Type INT,
Points_Awarded INT
);

CREATE TABLE RECYCLEPROJECT(
ProjID INT IDENTITY(1,1) PRIMARY KEY,
Proj_Name VARCHAR(35),
Proj_Description VARCHAR(35),
Proj_Due DATE
);

CREATE TABLE RECORDEDITEM(
RecordedItemID INT IDENTITY(1,1) PRIMARY KEY,
StudentID INT FOREIGN KEY(StudentID) REFERENCES STUDENT(StudentID),
ItemID INT FOREIGN KEY(ItemID) REFERENCES ITEM(ItemID),
Date_Received DATE,
NumBags_Received INT
);

CREATE TABLE STUDENTMERIT(
StudentID INT NOT NULL,
MeritID INT NOT NULL,
CONSTRAINT PK_Student_Merit PRIMARY KEY(StudentID,MeritID),
FOREIGN KEY (StudentID) REFERENCES STUDENT(StudentID),
FOREIGN KEY (MeritID) REFERENCES MERIT(MeritID),
Date_Awarded DATE,
);

CREATE TABLE STUDENTONPROJECT(
ProjID INT NOT NULL,
StudentID INT NOT NULL,
CONSTRAINT PF_Student_On_Project PRIMARY KEY(ProjID,StudentID),
FOREIGN KEY (ProjID) REFERENCES RECYCLEPROJECT(ProjID),
FOREIGN KEY (StudentID) REFERENCES STUDENT(StudentID)
);
